training:
  test_size: 0.2
  validation_size_within_train: 0.1
  batch_size: 32
  learning_rate: 0.001
  epochs: 100
  optimizer: "adam"

data:
  raw_data_dir: "data/raw"
  clustered_data_path: "data/processed/clustered.csv"
  train_path: "data/processed/train.csv"
  val_path: "data/processed/val.csv"
  dbscan_clustering_plot_path: "data/figures/dbscan_clustering.png"
  bayesian_opt_progress_path: "data/figures/bayesian_opt_progress.png"

clustering:
  pca_n_components: 2
  dbscan_epsilon: 0.5  # Chosen based on k-distance graph
  dbscan_min_samples: 26 # DBSCAN parameters are chosen after trial and error


model:
  architecture: "resnet50"
  num_classes: 10
  save_path: "models/model.pth"

bayesian_optimization:
  hidden_dim: 
    min: 64
    max: 256
  num_layers: 
    min: 2
    max: 5
  dropout_rate: 
    min: 0.1
    max: 0.5
  lr: 
    min: 0.0001
    max: 0.01
  init_points: 5
  n_iter: 15
