training:
  test_size_for_clustering: 0.2
  train_size: 0.9
  validation_size_within_train: 0.1
  batch_size: 32
  epochs: 100

data:
  raw_data_dir: "data/raw"
  clustered_data_path: "data/processed/clustered.csv"
  train_path: "data/processed/train.csv"
  val_path: "data/processed/val.csv"
  dbscan_clustering_plot_path: "data/figures/dbscan_clustering.png"
  bayesian_opt_progress_path: "data/figures/bayesian_opt_progress.png"
  bayesian_opt_best_parameters_path: "data/processed/bayesian_opt_best_parameters.json"
  in_prediction_path: "data/figures/in_prediction.png"
  ood_prediction_path: "data/figures/ood_prediction.png"

clustering:
  pca_n_components: 2
  dbscan_epsilon: 0.5  # Chosen based on k-distance graph
  dbscan_min_samples: 26 # DBSCAN parameters are chosen after trial and error

model:
  save_path: "models/model.pth"
  device: "cpu"

bayesian_optimization:
  hidden_dim: 
    min: 64
    max: 256
  num_layers: 
    min: 2
    max: 5
  dropout_rate: 
    min: 0.1
    max: 0.5
  lr: 
    min: 0.0001
    max: 0.01
  init_points: 5
  n_iter: 15

hessian:
  model_eig_max_path: "models/model_eig_max.pt"
  model_eig_min_path: "models/model_eig_min.pt"
  trained_data_loss_landscape_path: "data/figures/trained_data_loss_landscape_path.png"
  test_id_data_loss_landscape_path: "data/figures/test_id_data_loss_landscape_path.png"
  test_ood_data_loss_landscape_path: "data/figures/test_ood_data_loss_landscape_path.png"
  test_id_ood_diff_loss_landscape_path: "data/figures/test_id_ood_diff_loss_landscape_path.png"

loss_landscape:
  distance: 0.3
  steps: 40